import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={(inter.className, ' flex')}>
        <div className="w-60 border-r h-screen border-gray-400 ">
          <Sidebar children={undefined}/>
        </div>
        <main className="w-full">
          {children}
        </main>
      </body>
    </html>
  );
}
